print ('All in one calculator')
print ('Put the first number of your choice')
num1 = input ("First Number: ")
print ('Then put the second number of your choice')
num2 = input ("Second Number: ")
sum = int (num1) + int (num2)
difference = int (num1) - int (num2)
Quotient = int (num1) // int(num2)
multiply = int (num1) * int (num2)
modulo = int (num1) % int (num2)
print ('---------------->')
print ('The Sum')
print (sum)
print ('---------------->')
print ('The Difference')
print (difference)
print ('---------------->')
print ('The Quotient')
print (Quotient)
print ('---------------->')
print ('The multiplication')
print (multiply)
print ('---------------->')
print ('The Modulo')
print ('modulo')
print ('---------------------->')
print ('Thank you for using My CalcuLator')
print ('PROGRAMMING IS NOT EASY, BUT IF YOU PRACTICE IT EVERYDAY IT WILL BE EASY AND FUN')
print ('Credits: => Mr Trojan, Sh1m1zu')
